# Generated by Django 6.0 on 2026-01-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_payment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='reason',
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
    ]
