# Generated by Django 6.0 on 2026-01-18 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='hospital.meeting'),
        ),
    ]
