# Generated by Django 6.0 on 2026-01-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_payment_doctor_payment_hospital_payment_meeting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='admitted_on',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='disease',
        ),
    ]
