# Generated by Django 6.0 on 2026-01-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_admitpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitpatient',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
